// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using CoreGraphics;

namespace AppFireBase
{
	public partial class ChatViewController : UIViewController
	{

        private const float FieldHeight = 44.0f;
        private const float FieldHMargin = 10.0f;
        private const float FieldFontSize = 16.0f;
        private const float FieldFloatingLabelFontSize = 11.0f;

        Utilidades objUtilidades;

		public ChatViewController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad()
		{
            base.ViewDidLoad();


            objUtilidades = new Utilidades(this);



            float topOffset = (float)(UIApplication.SharedApplication.StatusBarFrame.Size.Height + NavigationController.NavigationBar.Frame.Size.Height);
            UIColor floatingLabelColor = UIColor.Gray, floatingLabelActiveColor = UIColor.Blue;

            var titleField = new FloatLabeledTextField(new CGRect(x:16, y:85, width: 346,
                                                                  height:45))
            {
                Placeholder = "Title",
                Font = UIFont.SystemFontOfSize(FieldFontSize),
                ClearButtonMode = UITextFieldViewMode.WhileEditing,
                FloatingLabelFont =  UIFont.SystemFontOfSize(16),
                FloatingLabelTextColor = floatingLabelColor,
                FloatingLabelActiveTextColor = floatingLabelActiveColor
            };

            var borderLine = new UIView(new CGRect(x: 0, y: titleField.Frame.Height + 1.0, width: titleField.Frame.Width, height: 1.0));

            borderLine.BackgroundColor = objUtilidades.FromHexString("#0094ff");

            titleField.AddSubview(borderLine);


            View.AddSubview(titleField);

		}
            
	}
}
