// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using Firebase;
using Firebase.Database;
using System.Collections.Generic;

namespace AppFireBase
{
	public partial class PrincipalViewController : UIViewController
	{
        DatabaseReference referenceBD;

        NSUserDefaults nSUserDefaults = new NSUserDefaults();

        List<Productos> listaProductos;

		public PrincipalViewController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad()
		{
            base.ViewDidLoad();

            referenceBD = Database.DefaultInstance.GetRootReference();

            listaProductos = new List<Productos>();

            crearUsuario();

            Tabla.Source = new TableSource(listaProductos, this);
            Tabla.ReloadData();

           /* InvokeOnMainThread(() =>
            {
                ConsultarProductos();
            });*/

		}


        void ConsultarProductos(){

            listaProductos.Clear();

            DatabaseReference productos = referenceBD.GetChild("Productos");

            nuint handleReference = productos.ObserveEvent(DataEventType.Value, (snapshot) =>
            {
                var data = snapshot.GetValue<NSDictionary>();

                var producto = new Productos
                {
                    Nombre = data["Nombre"].ToString(),
                    Existencia = data["Existencia"].ToString()
                };

                listaProductos.Add(producto);

                Tabla.ReloadData();

            });
        }



        public void crearUsuario(){

            DatabaseReference NodoUsuarios = referenceBD.GetChild("Usuarios").GetChild(nSUserDefaults.StringForKey("IdUsuario"));

            object[] keys = { "Edad","Matricula","Fecha" };
            object[] values = { 29, 105596, DateTime.Now.ToString() };

            var data = NSDictionary.FromObjectsAndKeys(values, keys, keys.Length);

            NodoUsuarios.SetValue<NSDictionary>(data);

        }

		public override void ViewWillAppear(bool animated)
		{
            base.ViewWillAppear(animated);
            //Actualizar los datos
            /*InvokeOnMainThread(() =>
            {
                ConsultarProductos();
            });*/
		}
	}
}
