// This file has been autogenerated from a class added in the UI designer.

using System;
using Foundation;
using UIKit;

namespace UINavigationController4
{
	public partial class SegundaViewcontroller : UIViewController
	{
        public string informacion { get; set; }

        public SegundaViewcontroller (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            lblInformacion.Text = informacion;          
        }
	}
}
